#____________________________________________________________________________________________
# align_axis(target_vect, source_vect, axis, ref)
#____________________________________________________________________________________________

float64[3] target_vect       # target vector[3]  
float64[3] source_vect       # source vector[3]  
int8       axis              # DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) 
int8       ref               # DR_BASE(0), DR_WORLD(2), user coord(101~200)
                             # <ref is only available in M2.40 or later> 
---
bool       success 