#____________________________________________________________________________________________
# get_workpiece_weight
#____________________________________________________________________________________________

---
float32       weight               # Measured weight, Negative value if error
bool          success