#____________________________________________________________________________________________
# is_done_bolt_tightening  
#____________________________________________________________________________________________

float64    m                 # Target torque  
float64    timeout           # Monitoring duration [sec]  
int8       axis              # DR_AXIS_X(0), DR_AXIS_Y(1), DR_AXIS_Z(2) 
---
bool       success