#____________________________________________________________________________________________
# overwrite_user_cart_coord   
#____________________________________________________________________________________________
# This service is only available in M2.50 or later

int8       id                # ID of user coord 
float64[6] pos               # task pos(posx)  
int8       ref        #= 0   # DR_BASE(0), DR_WORLD(2)
---
int8       id                # Successful coordinate setting, Set user coordinate ID (101 - 200)
                             # (-1) Failed coordinate setting
bool       success                             