#____________________________________________________________________________________________
# release_force  
#____________________________________________________________________________________________

float64    time # 0          # Time needed to reduce the force (0 ~ 1.0) 
---
bool       success 