#____________________________________________________________________________________________
# release_compliance_ctrl  
#____________________________________________________________________________________________

---
int8       res               # 0=success, otherwise fail 