#____________________________________________________________________________________________
# reset_workpiece_weight
# Initializes the weight data of the material to initialize the algorithm before measuring the weight of the material.
# ____________________________________________________________________________________________

---
bool       success 