#____________________________________________________________________________________________
# connect_rt_control
#____________________________________________________________________________________________

string     ip_address
uint32     port
---
bool       success