#____________________________________________________________________________________________
# disconnect_rt_control
#____________________________________________________________________________________________
---
bool       success