#____________________________________________________________________________________________
# get_rt_control_input_version_list
#____________________________________________________________________________________________

---
bool       success
string     version