#____________________________________________________________________________________________
# get_rt_control_output_data_list
#____________________________________________________________________________________________

string     version
---
bool       success
string     data