#____________________________________________________________________________________________
# get_rt_control_output_version_list
#____________________________________________________________________________________________

---
bool       success
string     version