#____________________________________________________________________________________________
# get_rt_control_input_data_list
#____________________________________________________________________________________________
string     version
---
bool       success
string     data