#____________________________________________________________________________________________
# read_data_rt
#____________________________________________________________________________________________

---
RobotStateRT       data