#____________________________________________________________________________________________
# set_accj_rt
#____________________________________________________________________________________________
float64[6] acc
---
bool       success