#____________________________________________________________________________________________
# set_rt_control_input
#____________________________________________________________________________________________
string     version
float64    period
int32      loss
---
bool       success