#____________________________________________________________________________________________
# set_rt_control_output
#____________________________________________________________________________________________
string     version
float64    period
int32      loss
---
bool       success