#____________________________________________________________________________________________
# set_velx_rt
#____________________________________________________________________________________________
float64    trans
float64    rotation
---
bool       success