#____________________________________________________________________________________________
# start_rt_control
#____________________________________________________________________________________________

---
bool       success