#____________________________________________________________________________________________
# stop_rt_control
#____________________________________________________________________________________________
---
bool       success