#____________________________________________________________________________________________
# [ robot error msg ] 
#____________________________________________________________________________________________

int32	    level   # INFO =1, WARN =2, ERROR =3 
int32	    group   # SYSTEM =1, MOTION =2, TP =3, INVERTER =4, SAFETY_CONTROLLER =5   
int32	    code    # error code 
string      msg1    # error msg 1
string      msg2    # error msg 2
string      msg3    # error msg 3