#____________________________________________________________________________________________
# get_analog_input 
#____________________________________________________________________________________________

int8        channel    # 1 = ch1, 2= ch2
---
float64     value
bool        success