#____________________________________________________________________________________________
# get_digital_input
# This service reads the I/O signals from digital contact points of the controller and reads the digital input contact value.
#____________________________________________________________________________________________

int8        index    # Digital Input in Control Box(1 ~ 16) 
                     # <GPIO_CTRLBOX_DIGITAL_INDEX>
---
int8        value    # 0=OFF, 1=ON
bool        success