#____________________________________________________________________________________________
# get_tool_digital_input  
# This service gets the current controlbox io output status.
#____________________________________________________________________________________________

int8        index    # Digital Input in Flange(1 ~ 6) 
                     # <GPIO_TOOL_DIGITAL_INDEX> 
---
int8        value    # 0=OFF, 1=ON
bool        success