#____________________________________________________________________________________________
# set_ctrl_box_analog_input_type  
#____________________________________________________________________________________________

int8        channel  # 1 = ch1, 2= ch2 
int8        mode     # 0 = current, 1 = voltage
---
bool        success