#____________________________________________________________________________________________
# set_ctrl_box_analog_output  
#____________________________________________________________________________________________

int8        channel  # 1 = ch1, 2= ch2 
float64     value   #
---
bool        success