#____________________________________________________________________________________________
# set_tool_digital_output  
# This service sends ouptput to tool io.
#____________________________________________________________________________________________

int8       index   # flange digital output port(1 ~ 6)
int8       value   # 0 : ON, 1 : OFF
---
bool       success