#____________________________________________________________________________________________
# get_current_rotm(ref)  
#____________________________________________________________________________________________
# This service returns the direction and matrix of the current tool based on the ref coordinate.

int8        ref               # DR_BASE(0), DR_WORLD(2)
---
std_msgs/Float64MultiArray[] rot_matrix  # target[3][3] Rotation matrix
bool        success