#____________________________________________________________________________________________
# get_current_velj()  
#____________________________________________________________________________________________
# This service returns the current target joint velocity. It cannot be used in the movel, movec, movesx, moveb, move_spiral, or move_periodic command.

---
float64[6]  joint_speed               # joint speed 
bool        success