#____________________________________________________________________________________________
# get_current_solution_space
#____________________________________________________________________________________________
# This service returns the current solution space value.

---
int8        sol_space         # solution space : 0 ~ 7
bool        success