#____________________________________________________________________________________________
# get_current_posj()  
#____________________________________________________________________________________________
# This service returns the current joint angle.

---
float64[6] pos               # joint pos(posj)  
bool       success