#____________________________________________________________________________________________
# get_desired_posj()  
#____________________________________________________________________________________________
# This service returns the current target joint angle.
# It cannot be used in the movel, movec, movesx, moveb, move_spiral, or move_periodic service.

---
float64[6] pos               # joint pos(posj)  
bool       success