#____________________________________________________________________________________________
# get_desired_velj()  
#____________________________________________________________________________________________

---
float64[6] joint_vel               # Target joint velocity 
