#____________________________________________________________________________________________
# get_joint_torque()
# returns the sensor torque value of the current joint.
#____________________________________________________________________________________________
# This service returns the sensor torque value of the current joint.

---
float64[6] jts         # value of JTS(Joint Torque Sensor) 
bool       success