#____________________________________________________________________________________________
# config_delete_modbus 
# It is a service to delete the Modbus I / O signal information registered 
# in advance in the robot controller 
#____________________________________________________________________________________________

string      name       # modbus signal symbol 
---
bool success