#____________________________________________________________________________________________
# set_modbus_output  
# This service sends the signal to an external Modbus system. 
#____________________________________________________________________________________________

string      name     # modbus signal symbol
int32       value    # modbus register value
---
bool        success