#____________________________________________________________________________________________
# change_operation_speed
#____________________________________________________________________________________________

int8 speed              # operation speed: (1~100)
---
bool success
