#____________________________________________________________________________________________
# disable_alter_motion  
# deactivates alter motion
#____________________________________________________________________________________________

---
bool success