#____________________________________________________________________________________________
# move_line  
#____________________________________________________________________________________________

float64[6] pos               # target  
float64[2] vel               # set velocity: [mm/sec], [deg/sec]
float64[2] acc               # set acceleration: [mm/sec2], [deg/sec2]
float64    time #= 0.0       # Time [sec] 
float64    radius #=0.0      # Radius under blending mode [mm] 
int8       ref               # DR_BASE(0), DR_TOOL(1), DR_WORLD(2)
                             # <DR_WORLD is only available in M2.40 or later> 
int8       mode #= 0         # DR_MV_MOD_ABS(0), DR_MV_MOD_REL(1) 
int8       blendType #= 0    # BLENDING_SPEED_TYPE_DUPLICATE=0, BLENDING_SPEED_TYPE_OVERRIDE=1
int8       syncType #=0      # SYNC = 0, ASYNC = 1
---
bool success