#____________________________________________________________________________________________
# move_wait
# This Service sets the waiting time between the previous motion command 
# and the motion command in the next line.
#____________________________________________________________________________________________

---
bool success