#____________________________________________________________________________________________
# stop()
# 인자 설명 추가 필요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#____________________________________________________________________________________________

int32 stop_mode         # DR_QSTOP_STO(0) : Quick stop (Stop Category 1 without STO(Safe Torque Off)
                        # DR_QSTOP(1)     : Quick stop (Stop Category 2)
                        # DR_SSTO(2)      : Soft Stop
                        # DR_HOLD(3)      : HOLD stop
---
bool success
