#____________________________________________________________________________________________
# set_singularity_handling
# 
#____________________________________________________________________________________________

int8       mode         # DR_AVOID(0)     : Automatic avoidance mode
                        # DR_TASK_STOP(1) : Deceleration/ Warning/ Task termination
                        # DR_VAR_VEL(2)   : Variable velocity mode

---
bool success
