#____________________________________________________________________________________________
# get_buttons_state
#____________________________________________________________________________________________

---
bool[5]       state