#____________________________________________________________________________________________
# get_current_pose
#____________________________________________________________________________________________

int8 space_type # 0=ROBOT_SPACE_JOINT, 1=ROBOT_SPACE_TASK
---
float64[6] pos
bool       success