#____________________________________________________________________________________________
# get_last_alarm
###Struct.LOG_ARARM
#____________________________________________________________________________________________

---
LogAlarm log_alarm
bool        success