#____________________________________________________________________________________________
# get_robot_system
#____________________________________________________________________________________________

---
int8 robot_system   # 0 : ROBOT_SYSTEM_REAL
                    # 1 : ROBOT_SYSTEM_VIRTUAL
bool        success