#____________________________________________________________________________________________
# get_robot_speed_mode
#____________________________________________________________________________________________

---
int8 speed_mode # 0 : SPEED_NORMAL_MODE
                # 1 : SPEED_REDUCED_MODE
bool        success   