#____________________________________________________________________________________________
# get_robot_mode
# Return to current robot-mode
# 0 : ROBOT_MODE_MANUAL
# 1 : ROBOT_MODE_AUTONOMOUS
# 2 : ROBOT_MODE_MEASURE
# drfl.GetRobotMode()
#____________________________________________________________________________________________

---
int8 robot_mode
bool        success