#____________________________________________________________________________________________
# get_robot_state
#____________________________________________________________________________________________

---
int8 robot_state    # 0 : STATE_INITIALIZING
                    # 1 : STATE_STANDBY
                    # 2 : STATE_MOVING
                    # 3 : STATE_SAFE_OFF
                    # 4 : STATE_TEACHING
                    # 5 : STATE_SAFE_STOP
                    # 6 : STATE_EMERGENCY_STOP:
                    # 7 : STATE_HOMMING
                    # 8 : STATE_RECOVERY
                    # 9 : eSTATE_SAFE_STOP2
                    # 10: STATE_SAFE_OFF2
                    # 11: STATE_RESERVED1
                    # 12: STATE_RESERVED2
                    # 13: STATE_RESERVED3
                    # 14: STATE_RESERVED4
                    # 15: STATE_NOT_READY
bool        success                    