#____________________________________________________________________________________________
# set_robot_mode
# Change the robot-mode
# 0 : ROBOT_MODE_MANUAL
# 1 : ROBOT_MODE_AUTONOMOUS
# 2 :ROBOT_MODE_MEASURE
# drfl.SetRobotMode()
#____________________________________________________________________________________________

int8 robot_mode # <Robot_Mode>
---
bool success
