#____________________________________________________________________________________________
# set_safety_mode
#____________________________________________________________________________________________

int8 safety_mode  
int8 safety_mode_event
---
bool success