#____________________________________________________________________________________________
# drl_script_resume  
# It is a service to resume the currently paused DRL program in the robot controller.    
#____________________________________________________________________________________________

---
bool success