#____________________________________________________________________________________________
# drl_script_stop  
# STOP_TYPE_QUICK_STO = 0
# STOP_TYPE_QUICK     = 1
# STOP_TYPE_SLOW      = 2
# STOP_TYPE_HOLD = STOP_TYPE_EMERGENCY = 3  
#____________________________________________________________________________________________

int8    stop_mode       # <STOP_TYPE> stop_mode       
---
bool    success