#____________________________________________________________________________________________
# get_drl_state
# Get DRL Program State
# 0 : DRL_PROGRAM_STATE_PLAY
# 1 : DRL_PROGRAM_STATE_STOP
# 2 : DRL_PROGRAM_STATE_HOLD
# 3 : DRL_PROGRAM_STATE_LAST
# drfl.GetProgramState()
#____________________________________________________________________________________________

---
int8        drl_state # <DRL_PROGRAM_STATE>
bool        success