#____________________________________________________________________________________________
# config_create_tcp  
# It is a service for registering and using robot TCP information in advance for safety
#____________________________________________________________________________________________

string          name         # tcp name 
float64[6]      pos          # coordinates of the TCP 
---
bool success