#____________________________________________________________________________________________
# config_delete_tcp  
# It is a service for deleting the TCP information registered in advance in the robot controller
#____________________________________________________________________________________________

string          name             # tcp name 
---
bool success