#____________________________________________________________________________________________
# set_current_tcp  
# It is a service that sets the information about the currently installed TCP
#____________________________________________________________________________________________

string         name # tcp name
---
bool           success