#____________________________________________________________________________________________
# robotiq_2f_open
# open the virtual robotiq gripper  
#____________________________________________________________________________________________

# None  
---
bool success