#____________________________________________________________________________________________
# robotiq_2f_move
# open or close the virtual robotiq gripper by input value(width)   
#____________________________________________________________________________________________

float64 width # 0.0(open) ~ 0.8(close)
---
bool success
