#____________________________________________________________________________________________
# serial_send_data
# send byte data to other device 
# you can operate the real-robotiq gripper by modbus rtu
#____________________________________________________________________________________________

string data
---
bool success