#____________________________________________________________________________________________
# config_delete_tool  
# It is a service to delete tool information registered in advance in the robot controller
#____________________________________________________________________________________________

string          name        # tool name 
---
bool success