#____________________________________________________________________________________________
# set_current_tool
# It is a service to set information about currently installed tool.  
#____________________________________________________________________________________________

string          name        # tool name
---
bool            success