#____________________________________________________________________________________________
# set_tool_shape
# It is a service to set information about currently installed tool.  
# Activates the tool shape information of the entered name among the tool shape information registered in the Teach Pendant
#____________________________________________________________________________________________

string          name        # Tool name registered in the Teach Pendant
---
bool            success